#include "cycloarm.h"
#ifndef CONFIG_H
#define CONFIG_H

#define BAUD_RATE 115200
#define MOTION_BUFFER_SIZE 128

#define NO_DATA 0x00

#define BOARD_A_IDENT 0xf1
#define BOARD_B_IDENT 0xf2

#define MOTOR_STEPS_PER_REV 200

#define STEPPER_DELAY 800

#define BASE_MAX_SPEED 200
#define BASE_ACCEL 100
#define BASE_RR 10

#define SHOULDER_MAX_SPEED 1200
#define SHOULDER_ACCEL 200
#define SHOULDER_RR 75

#define ELBOW_MAX_SPEED 1200
#define ELBOW_ACCEL 200
#define ELBOW_RR 60

#define WRIST_ROLL_MAX_SPEED 200
#define WRIST_ROLL_ACCEL 100
#define WRIST_ROLL_RR 20

#define WRIST_LEFT_MAX_SPEED 200
#define WRIST_LEFT_ACCEL 100
#define WRIST_LEFT_RR 5

#define WRIST_RIGHT_MAX_SPEED 200
#define WRIST_RIGHT_ACCEL 100
#define WRIST_RIGHT_RR 5

#define GRIPPER_MAX_SPEED 200
#define GRIPPER_ACCEL 100
#define GRIPPER_RR 1

#endif