#include "cycloarm.h"
#ifndef CONFIG_H
#define CONFIG_H

#define BAUD_RATE 115200

#define NO_DATA 0x00

#define BOARD_A_IDENT 0xf1
#define BOARD_B_IDENT 0xf2

#define MOTOR_STEPS_PER_REV 200

#define STEPPER_DELAY 800

#define BASE_MAX_SPEED 200
#define BASE_ACCEL 100

#define SHOULDER_MAX_SPEED 200
#define SHOULDER_ACCEL 100

#define ELBOW_MAX_SPEED 200
#define ELBOW_ACCEL 100

#define WRIST_ROLL_MAX_SPEED 200
#define WRIST_ROLL_ACCEL 100

#define WRIST_LEFT_MAX_SPEED 200
#define WRIST_LEFT_ACCEL 100

#define WRIST_RIGHT_MAX_SPEED 200
#define WRIST_RIGHT_ACCEL 100

#endif